version: '3'
services:
  docker-mysql:
    restart : always
    container_name : docker-mysql
    image : mysql
    environment :
      MYSQL_DATABASE : wishlist_manager
      MYSQL_ROOT_PASSWORD : root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"

  wishlist-app:
    restart: on-failure
    build: ./
    expose:
      - "10223"
    ports:
      - 10223:10223
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql